In [2]:
import requests
import json
import pandas as pd

In [3]:
limit = 10000000
disease_url = f'https://data.cdc.gov/resource/x9gk-5huc.json?$limit={limit}'

In [4]:
data = requests.get(disease_url)
data

In [5]:
data = data.json()
# print(json.dumps(data, indent=4))

In [6]:
df = pd.DataFrame(data)
df

,states,year,week,label,m1_flag,m2,m2_flag,m3_flag,m4_flag,location2,sort_order,location1,geocode,:@computed_region_hjsp_umg2,:@computed_region_skr5_azej,m4,m1,m3
0,US RESIDENTS,2022,1,Anthrax,-,0,-,-,-,US RESIDENTS,20220100001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NEW ENGLAND,2022,1,Anthrax,-,0,-,-,-,NEW ENGLAND,20220100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CONNECTICUT,2022,1,Anthrax,-,0,-,-,-,NaN,20220100003,CONNECTICUT,"{'type': 'Point', 'coordinates': [-72.738288, ...",24,1043,NaN,NaN,NaN
3,MAINE,2022,1,Anthrax,-,0,-,-,-,NaN,20220100004,MAINE,"{'type': 'Point', 'coordinates': [-69.06137, 4...",49,1725,NaN,NaN,NaN
4,MASSACHUSETTS,2022,1,Anthrax,-,0,-,-,-,NaN,20220100005,MASSACHUSETTS,"{'type': 'Point', 'coordinates': [-71.481104, ...",25,1916,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1116775,GUAM,2024,40,"Zika virus disease, non-congenital",-,0,-,-,-,NaN,20244008186,GUAM,"{'type': 'Point', 'coordinates': [144.76945169...",NaN,NaN,NaN,NaN,NaN
1116776,PUERTO RICO,2024,40,"Zika virus disease, non-congenital",-,3,-,-,-,NaN,20244008187,PUERTO RICO,"{'type': 'Point', 'coordinates': [-66.46895343...",NaN,3087,27,NaN,9
1116777,U.S. VIRGIN ISLANDS,2024,40,"Zika virus disease, non-congenital",-,0,-,-,-,NaN,20244008188,U.S. VIRGIN ISLANDS,"{'type': 'Point', 'coordinates': [-64.8190875,...",NaN,NaN,NaN,NaN,NaN
1116778,NON-US RESIDENTS,2024,40,"Zika virus disease, non-congenital",-,0,-,-,-,NON-US RESIDENTS,20244008189,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116779,TOTAL,2024,40,"Zika virus disease, non-congenital",-,4,-,-,-,TOTAL,20244008190,NaN,NaN,NaN,NaN,31,NaN,23

In [7]:
df.columns

Index(['states', 'year', 'week', 'label', 'm1_flag', 'm2', 'm2_flag',
       'm3_flag', 'm4_flag', 'location2', 'sort_order', 'location1', 'geocode',
       ':@computed_region_hjsp_umg2', ':@computed_region_skr5_azej', 'm4',
       'm1', 'm3'],
      dtype='object')

In [8]:
df["label"].unique()

array(['Anthrax', 'Arboviral diseases, Chikungunya virus disease',
       'Arboviral diseases, Eastern equine encephalitis virus disease',
       'Arboviral diseases, Jamestown Canyon  virus disease',
       'Arboviral diseases, La Crosse  virus disease',
       'Arboviral diseases, Powassan virus disease',
       'Arboviral diseases, St. Louis encephalitis virus disease',
       'Arboviral diseases, West Nile virus disease',
       'Arboviral diseases, Western equine encephalitis virus disease',
       'Babesiosis', 'Botulism, Foodborne', 'Botulism, Infant',
       'Botulism, Other (wound & unspecified)', 'Brucellosis',
       'Campylobacteriosis', 'Candida auris, clinical',
       'Carbapenemase-producing carbapenem-resistant Enterobacteriaceae',
       'Chancroid', 'Chlamydia trachomatis infection', 'Cholera',
       'Coccidioidomycosis', 'Cryptosporidiosis', 'Cyclosporiasis',
       'Dengue virus infections, Dengue',
       'Dengue virus infections, Dengue-like illness',
       'Dengue virus infections, Severe dengue',
       'Ehrlichiosis and Anaplasmosis, Anaplasma phagocytophilum infection',
       'Ehrlichiosis and Anaplasmosis, Ehrlichia chaffeensis infection',
       'Ehrlichiosis and Anaplasmosis, Ehrlichia ewingii infection',
       'Ehrlichiosis and Anaplasmosis, Undetermined ehrlichiosis/anaplasmosis',
       'Giardiasis', 'Gonorrhea',
       'Haemophilus influenzae, invasive disease, Age <5 years, Non-b serotype',
       'Haemophilus influenzae, invasive disease, Age <5 years, Nontypeable',
       'Haemophilus influenzae, invasive disease, Age <5 years, Serotype b',
       'Haemophilus influenzae, invasive disease, Age <5 years, Unknown serotype',
       'Haemophilus influenzae, invasive disease, All ages, all serotypes',
       "Hansen's disease",
       'Hantavirus infection, non-hantavirus pulmonary syndrome',
       'Hantavirus pulmonary syndrome',
       'Hemolytic uremic syndrome post-diarrheal',
       'Hepatitis B, perinatal infection',
       'Hepatitis C, acute, Confirmed', 'Hepatitis C, acute, Probable',
       'Hepatitis C, perinatal infection', 'Hepatitis, A, acute',
       'Hepatitis, B, acute', 'Influenza-associated pediatric mortality',
       'Invasive pneumococcal disease, age <5 years, Confirmed',
       'Invasive pneumococcal disease, age <5 years, Probable',
       'Invasive pneumococcal disease, all ages, Confirmed',
       'Invasive pneumococcal disease, all ages, Probable',
       'Legionellosis', 'Leptospirosis', 'Listeriosis, Confirmed',
       'Listeriosis, Probable', 'Malaria', 'Measles, Imported',
       'Measles, Indigenous', 'Meningococcal disease, All serogroups',
       'Meningococcal disease, Other serogroups',
       'Meningococcal disease, Serogroup B',
       'Meningococcal disease, Serogroups ACWY',
       'Meningococcal disease, Unknown serogroup', 'Mumps',
       'Novel Influenza A virus infections', 'Pertussis', 'Plague',
       'Poliomyelitis, paralytic', 'Poliovirus infection, nonparalytic',
       'Psittacosis', 'Q fever, Acute', 'Q fever, Chronic',
       'Q fever, Total', 'Rabies, Animal', 'Rabies, Human', 'Rubella',
       'Rubella, congenital syndrome', 'Salmonella Paratyphi infection',
       'Salmonella Typhi infection',
       'Salmonellosis (excluding Salmonella Typhi infection and Salmonella Paratyphi infection)',
       'Severe acute respiratory syndrome-associated coronavirus disease',
       'Shiga toxin-producing Escherichia coli (STEC)', 'Shigellosis',
       'Smallpox', 'Streptococcal toxic shock syndrome',
       'Syphilis, Congenital', 'Syphilis, Primary and secondary',
       'Tetanus', 'Toxic shock syndrome (other than Streptococcal)',
       'Trichinellosis', 'Tuberculosis', 'Tularemia',
       'Vancomycin-intermediate Staphylococcus aureus',
       'Vancomycin-resistant Staphylococcus aureus',
       'Varicella morbidity',
       'Vibriosis (any species of the family Vibrionaceae, other than toxigenic Vibrio cholerae O1 or O139), Confirmed',
       'Vibriosis (any species of the family Vibrionaceae, other than toxigenic Vibrio cholerae O1 or O139), Probable',
       'Viral hemorrhagic fevers, Chapare virus',
       'Viral hemorrhagic fevers, Crimean-Congo hemorrhagic fever virus',
       'Viral hemorrhagic fevers, Ebola virus',
       'Viral hemorrhagic fevers, Guanarito virus',
       'Viral hemorrhagic fevers, Junin virus',
       'Viral hemorrhagic fevers, Lassa virus',
       'Viral hemorrhagic fevers, Lujo virus',
       'Viral hemorrhagic fevers, Machupo virus',
       'Viral hemorrhagic fevers, Marburg virus',
       'Viral hemorrhagic fevers, Sabia virus', 'Yellow fever',
       'Zika virus disease, non-congenital', 'Candida auris, screening',
       'Carbapenemase-Producing Organisms (CPO), Total',
       'Coccidioidomycosis, Confirmed', 'Coccidioidomycosis, Probable',
       'Coccidioidomycosis, total', 'Melioidosis',
       'Hepatitis A, Confirmed', 'Hepatitis B, acute',
       'Hepatitis B, perinatal, Confirmed',
       'Hepatitis C, perinatal, Confirmed', 'Varicella disease',
       'Cronobacter invasive infection, infants, Confirmed',
       'Cronobacter invasive infection, infants, Probable',
       'Hepatitis B, acute, Confirmed', 'Hepatitis B, acute, Probable',
       'Hepatitis B, chronic, Confirmed',
       'Hepatitis B, chronic, Probable',
       'Hepatitis C, chronic, Confirmed',
       'Hepatitis C, chronic, Probable', 'Mpox'], dtype=object)

In [10]:
df['year'].unique()

array(['2022', '2023', '2024'], dtype=object)

In [18]:
url = f'https://data.cdc.gov/resource/u6jv-9ijr.json?$limit={limit}'

In [19]:
data = requests.get(url)
data

In [20]:
data = data.json()

In [21]:
df = pd.DataFrame(data)
df

,jurisdiction,week_ending_date,state_abbreviation,mmwryear,mmwrweek,cause_group,number_of_deaths,cause_subgroup,time_period,average_number_of_deaths,type,difference_from_2015_2019_to_2020,percent_difference_from_15_19_to_20,note
0,New Jersey,2018-02-03T00:00:00.000,NJ,2018,5,Other select causes,49,Sepsis,2015-2019,42,Predicted (weighted),NaN,NaN,NaN
1,Alabama,2015-01-10T00:00:00.000,AL,2015,1,Other select causes,22,Sepsis,2015-2019,24,Predicted (weighted),NaN,NaN,NaN
2,Alabama,2015-01-10T00:00:00.000,AL,2015,1,Other select causes,22,Sepsis,2015-2019,24,Unweighted,NaN,NaN,NaN
3,Alabama,2016-01-09T00:00:00.000,AL,2016,1,Other select causes,13,Sepsis,2015-2019,24,Predicted (weighted),NaN,NaN,NaN
4,Alabama,2016-01-09T00:00:00.000,AL,2016,1,Other select causes,13,Sepsis,2015-2019,24,Unweighted,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481135,Oregon,2023-04-22T00:00:00.000,OR,2023,16,Alzheimer disease and dementia,77,Alzheimer disease and dementia,2023,77,Predicted (weighted),-2,-2.5,Data in recent weeks are incomplete. Only 60% ...
481136,Oregon,2022-04-23T00:00:00.000,OR,2022,16,Alzheimer disease and dementia,98,Alzheimer disease and dementia,2022,98,Unweighted,NaN,NaN,Data in recent weeks are incomplete. Only 60% ...
481137,Oregon,2022-04-23T00:00:00.000,OR,2022,16,Alzheimer disease and dementia,98,Alzheimer disease and dementia,2022,98,Predicted (weighted),19,24.1,Data in recent weeks are incomplete. Only 60% ...
481138,Oregon,2021-04-24T00:00:00.000,OR,2021,16,Alzheimer disease and dementia,79,Alzheimer disease and dementia,2021,79,Unweighted,NaN,NaN,NaN
481139,Oregon,2021-04-24T00:00:00.000,OR,2021,16,Alzheimer disease and dementia,79,Alzheimer disease and dementia,2021,79,Predicted (weighted),0,0,NaN

In [22]:
df['time_period'].unique()

array(['2015-2019', '2020', '2021', '2022', '2023'], dtype=object)

In [23]:
df['cause_group'].unique()

array(['Other select causes', 'Respiratory diseases',
       'Circulatory diseases', 'Malignant neoplasms',
       'Alzheimer disease and dementia'], dtype=object)